name: Build uYouEnhanced Dylib

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK Version"
        default: "17.5"
        required: true
        type: string
      commit_id:
        description: "(Optional) Commit ID to build at"
        default: ""
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Dylib
    runs-on: macos-14

    steps:
      - name: Checkout Main
        uses: actions/checkout@v5
        with:
          path: main
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Setup Theos
        uses: actions/checkout@v5
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4.3.0
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/aricloverALT/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build Tweak (Dylib Only)
        run: |
          cd ${{ github.workspace }}/main
          sed -i '' "1s#.*#export TARGET = iphone:clang:${{ inputs.sdk_version }}:14.0#g" Makefile
          gmake clean
          gmake
          echo "Build complete"
          find .theos -name "*.dylib"

        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v5
        with:
          name: uYouEnhanced-dylib
          path: main/.theos/obj/**/*.dylib
          if-no-files-found: error
